### ISSUE TITLE
return/echo is not working after exe conversion

### ISSUE THREAD

**Issue by GeethaSelvam** [aravindvcyber/PS1toEXE#2]
Hi @aravindvcyber ,
  I am trying to encrypt a password and return encrypted password value using a exe file by passing the plain text password as pipeline parameter.
I have achieved the same using powershell(.\EncryptPassword.ps1 -CurrentPass pass123) .
But after converting it into exe file using this module .I am not able to get the encrypted password in the console.
Kindly help!!

**Comment by aravindvcyber** [comment]
Thanks Geetha, for your issue identification, i believe it is due to the placement of params to the exe, let me check may be our community can help soon, i will find some time to fix this when i find a windows machine.

**Comment by aravindvcyber** [comment]
I think you have to run the exe which is the output like this in some batch file or in cmd window.

`EncryptPassword.exe -CurrentPass pass123`
